language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
after_success:
  - rm -rf reports
  - mkdir reports
  - gulp test --silent >.tmp/coverage.tmp 2>/tmp/err.log
  - cat .tmp/coverage.tmp | grep -v "\[conflict\]" > reports/coverage.html
